# Generated by Django 3.2.5 on 2021-07-17 10:47

import customers_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Başında 0 olmadan 10 haneli ve bitişik biçimde girin.', max_length=10, validators=[customers_app.validators.phone_number_validator], verbose_name='Telefon Numarası'),
        ),
    ]
