# Generated by Django 3.2.5 on 2021-07-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-pk']},
        ),
    ]
